### ISSUE TITLE
Is it compatible with the RobotDyn AC Dimmer ?

### ISSUE THREAD

**Issue by mathieucarbou** [pmarchini/Esp32Dimmer#6]
Thanks :-)

**Comment by pmarchini** [comment]
Hey!

Yes, it is!
In general it's compatible with every TRIAC-based AC Dimmer!

If you have any doubt feel free to ask!!!

**Comment by mathieucarbou** [comment]
Thanks a lot! I will try it :-)

**Comment by mathieucarbou** [comment]
Note: this is for an OSS project (soon on github) for a solar router

**Comment by pmarchini** [comment]
> Note: this is for an OSS project (soon on github) for a solar router

Very interesting!!!

Let me know when the project is online 🚀

**Comment by mathieucarbou** [comment]
Of course!
