### ISSUE TITLE
Estou enfentando um problema com a junção da biblioteca DHT_22, quando inicializado a função init() do dimer a variações no funionamento da leitura do dht22 creio que devido os timers usados para funcionamento do dimmer. Poderia ajudar em uma solução?

### ISSUE THREAD

**Issue by edil-project** [pmarchini/Esp32Dimmer#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pmarchini** [comment]
Hey!

Can you please share the DHT_22 library you're using in your project?

**Comment by edil-project** [comment]
Estou usando essa lib, https://github.com/Andrey-m/DHT22-lib-for-esp-idf/tree/master/include
